#!/bin/bash
set -e
export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD';
	CREATE DATABASE $APP_DB_NAME;
	ALTER DATABASE $APP_DB_NAME OWNER TO $APP_DB_USER;
	GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  ALTER ROLE $APP_DB_USER SET client_encoding TO 'utf8';
  ALTER ROLE $APP_DB_USER SET default_transaction_isolation TO 'read committed';
  ALTER ROLE $APP_DB_USER SET timezone TO 'UTC';
EOSQL