# Generated by Django 4.2.3 on 2023-07-30 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField()),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('modified_by', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DRAFT', 'DRAFT'), ('OUTDATED', 'OUTDATED')], default='DRAFT')),
                ('steps', models.JSONField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.project')),
                ('suit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='management_system.suit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TCHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('modified_by', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DRAFT', 'DRAFT'), ('OUTDATED', 'OUTDATED')], default='DRAFT')),
                ('steps', models.JSONField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.project')),
                ('suit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='management_system.suit')),
                ('tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.tc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
