# Generated by Django 4.2.3 on 2023-08-01 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField()),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('modified_by', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DRAFT', 'DRAFT'), ('OUTDATED', 'OUTDATED')], default='DRAFT')),
                ('steps', models.JSONField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.project')),
                ('suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.suit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TCinTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_status', models.CharField(choices=[('IN PROGRESS', 'IN PROGRESS'), ('SUCCEED', 'SUCCEED'), ('FAILED', 'FAILED'), ('SKIPPED', 'SKIPPED')], default='IN PROGRESS')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.tc')),
            ],
        ),
        migrations.CreateModel(
            name='TP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('modified_by', models.IntegerField()),
                ('status', models.CharField(choices=[('IN PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED')], default='IN PROGRESS', null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('proj', models.ManyToManyField(to='management_system.project')),
                ('suit', models.ManyToManyField(to='management_system.suit')),
                ('tc', models.ManyToManyField(to='management_system.tcintp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TCHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('modified_by', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DRAFT', 'DRAFT'), ('OUTDATED', 'OUTDATED')], default='DRAFT')),
                ('steps', models.JSONField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.project')),
                ('suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.suit')),
                ('tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.tc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
