# Generated by Django 4.2.3 on 2023-08-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0002_suit_tc_tcintp_tp_tchistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tp',
            name='tc',
            field=models.ManyToManyField(to='management_system.tc'),
        ),
    ]
