# Generated by Django 4.2.3 on 2023-08-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0003_alter_tp_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tp',
            name='tc',
            field=models.ManyToManyField(to='management_system.tcintp'),
        ),
    ]
