# Generated by Django 4.2.3 on 2023-08-04 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0004_alter_tp_tc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tp',
            name='tc',
        ),
        migrations.AddField(
            model_name='tcintp',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management_system.tp'),
        ),
    ]
