# Generated by Django 4.2.3 on 2023-08-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('Owner', 'Owner'), ('Developer', 'Developer'), ('Tester', 'Tester')], default='ADMIN', max_length=20),
        ),
    ]
