# Generated by Django 4.2.3 on 2023-08-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0007_customuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='MEDIUM'),
        ),
        migrations.AddField(
            model_name='tchistory',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='MEDIUM'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Developer', 'Developer'), ('Tester', 'Tester')], default='Tester'),
        ),
    ]
